// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vertical360_back.Infrastructure.Persistence;

#nullable disable

namespace Vertical360_back.Migrations.CommonDb
{
    [DbContext(typeof(CommonDbContext))]
    [Migration("20251001050221_UpdateComapanies")]
    partial class UpdateComapanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Cities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Companies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserCreationId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserCreationId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Countries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("DepartamentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Departments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.LinkUserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompaniesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateTimeCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserIdentityId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("statusLink")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.HasIndex("UserIdentityId");

                    b.ToTable("LinkUsersCommpany");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.CompanyUserPermissions", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<Guid?>("CompaniesId")
                        .HasColumnType("char(36)");

                    b.HasKey("CompanyId", "UserId", "Permissions");

                    b.HasIndex("CompaniesId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUserPermissions");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Cities", b =>
                {
                    b.HasOne("Vertical360_back.Domain.Entityes.Common.Departments", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Companies", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UserCreation")
                        .WithMany()
                        .HasForeignKey("UserCreationId");

                    b.Navigation("UserCreation");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Countries", b =>
                {
                    b.HasOne("Vertical360_back.Domain.Entityes.Common.Departments", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Departments", b =>
                {
                    b.HasOne("Vertical360_back.Domain.Entityes.Common.Countries", "Country")
                        .WithMany("Departments")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.LinkUserCompany", b =>
                {
                    b.HasOne("Vertical360_back.Domain.Entityes.Common.Companies", "Companies")
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "UserIdentity")
                        .WithMany()
                        .HasForeignKey("UserIdentityId");

                    b.Navigation("Companies");

                    b.Navigation("UserIdentity");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.CompanyUserPermissions", b =>
                {
                    b.HasOne("Vertical360_back.Domain.Entityes.Common.Companies", "Companies")
                        .WithMany("CompanyUserPermissions")
                        .HasForeignKey("CompaniesId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Companies", b =>
                {
                    b.Navigation("CompanyUserPermissions");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Countries", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Vertical360_back.Domain.Entityes.Common.Departments", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
